version: "3"

services:
  server1:
    image: httpd:latest
    volumes:
      - ./server1/index.html:/usr/local/apache2/htdocs/index.html
    container_name: server1

  server2:
    image: httpd:latest
    volumes:
      - ./server2/index.html:/usr/local/apache2/htdocs/index.html
    container_name: server2

  nload_balancer: 
    build: . 
    container_name: loadbalancer
    ports:
      - 8080:8080
    depends_on: 
      - server1
      - server2
